### Hämta en kundvagn
GET {{$dotenv CART_SERVICE_URL}}/cart/18
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxOCIsIm5hbWUiOiJPcmRlciBTZXJ2aWNlIiwiZW1haWwiOiJ3YWNrc3Ryc0BhcmNhZGEuZmkiLCJyb2xlIjoidXNlciIsImV4cCI6MTc0MTE2Nzc4NH0.VxS2GiKCk9XTIh0KDiMyTN7IiIgG-YQqnr23EGE6FiE